/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import bancoDeDados.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.*;
import extra.Cpf;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.Icon;

/**
 *
 * @author alunom
 */
public class inicial extends javax.swing.JFrame {

    Icon imagem = (new ImageIcon("logoOuro.jpg"));
    String caminhoM = "";
    String usuarioM = "";
    String senhaM = "";

    Cpf cpf = new Cpf();
    TurmaBD turmabd = new TurmaBD();
    Turma turma = new Turma();
    ConvidadoBD convidadobd = new ConvidadoBD();
    Convidado convidado = new Convidado();
    ArrayList<Turma> listaTurma;
    ArrayList<Turma> listaTurmaSelecionadaTurno;
    int i = 0;

    public inicial(String caminho, String usuario, String senha) {

        this.caminhoM = caminho;
        this.usuarioM = usuario;
        this.senhaM = senha;

        initComponents();
             
        this.setSize(900, 700);
        this.getContentPane().setBackground(new Color(255, 255, 255));

     
        this.setTitle("Feira de Curso CEET ");

        //  atualizarBanco(-1);
        this.setLocationRelativeTo(null);
        cbxAluno.removeAllItems();
        cbxEscolaridade.removeAllItems();

        cbxEscolaridade.addItem("Fundamental completo");
        cbxEscolaridade.addItem("Médio incompleto");
        cbxEscolaridade.addItem("Médio completo");
        cbxEscolaridade.addItem("Técnico incompleto");
        cbxEscolaridade.addItem("Técnico completo");
        cbxEscolaridade.addItem("Superior incompleto");
        cbxEscolaridade.addItem("Superior completo");

        // this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btgTurno = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btCadastrarConvidado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfCPF = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfCelular = new javax.swing.JFormattedTextField();
        cbxEscolaridade = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbMatutino = new javax.swing.JRadioButton();
        rbVespertino = new javax.swing.JRadioButton();
        rbNoturno = new javax.swing.JRadioButton();
        cbxAluno = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miClassificacao = new javax.swing.JMenuItem();
        miCadastroConvidado = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Feira");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vasco6_fw.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 537, 182);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/feira3.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 205, 381, 477);

        btCadastrarConvidado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/accept.png"))); // NOI18N
        btCadastrarConvidado.setText("Cadastrar Convidado");
        btCadastrarConvidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarConvidadoActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrarConvidado);
        btCadastrarConvidado.setBounds(620, 590, 180, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("<html>Nome<font color='red'>*</font>:</html>");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 250, 60, 20);
        getContentPane().add(tfNome);
        tfNome.setBounds(530, 250, 270, 30);

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfCPF);
        tfCPF.setBounds(530, 280, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("<html>CPF<font color='red'>*</font>:</html>");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 280, 50, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("E-Mail:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 310, 50, 20);
        getContentPane().add(tfEmail);
        tfEmail.setBounds(530, 310, 210, 30);

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfTelefone);
        tfTelefone.setBounds(530, 350, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefone:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 350, 70, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("celular:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(420, 390, 60, 20);

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfCelular);
        tfCelular.setBounds(530, 390, 130, 30);

        cbxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxEscolaridade);
        cbxEscolaridade.setBounds(530, 430, 270, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Escolaridade:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 430, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Turma:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 540, 60, 20);

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Convidado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 200, 210, 30);

        btgTurno.add(rbMatutino);
        rbMatutino.setText("MATUTINO");
        rbMatutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMatutinoActionPerformed(evt);
            }
        });
        getContentPane().add(rbMatutino);
        rbMatutino.setBounds(450, 480, 93, 23);

        btgTurno.add(rbVespertino);
        rbVespertino.setText("VESPERTINO");
        rbVespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVespertinoActionPerformed(evt);
            }
        });
        getContentPane().add(rbVespertino);
        rbVespertino.setBounds(570, 480, 110, 23);

        btgTurno.add(rbNoturno);
        rbNoturno.setText("NOTURNO");
        rbNoturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoturnoActionPerformed(evt);
            }
        });
        getContentPane().add(rbNoturno);
        rbNoturno.setBounds(700, 480, 93, 23);

        cbxAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxAluno);
        cbxAluno.setBounds(540, 530, 260, 30);

        jMenu1.setText("Janelas");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miClassificacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        miClassificacao.setText("Classificação ");
        miClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClassificacaoActionPerformed(evt);
            }
        });
        jMenu1.add(miClassificacao);

        miCadastroConvidado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        miCadastroConvidado.setText("Cadastro de Convidado");
        miCadastroConvidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroConvidadoActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroConvidado);

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        jMenu1.add(miSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarConvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarConvidadoActionPerformed
        // TODO add your handling code here:
        if (tfCPF.getText().trim().isEmpty() || tfNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Os campos com * sao \n \t obrigatorios");
        } else {
            if (cpf.cfp(tfCPF.getText())) {
                convidado.setCpf(tfCPF.getText());
                convidado.setEmail(tfEmail.getText());
                convidado.setEscolaridade(cbxEscolaridade.getSelectedItem() + "");
                convidado.setNome(tfNome.getText());
                convidado.setTelefone(tfTelefone.getText());
                convidado.setCelular(tfCelular.getText());
                convidadobd.cadastrarConvidado(listaTurmaSelecionadaTurno.get(cbxAluno.getSelectedIndex()), convidado, this.caminhoM, this.usuarioM, this.senhaM);

                //convidadobd.cadastrarConvidado(listaTurma.get(cbxAluno.getSelectedIndex()), convidado);
                tfCPF.setText(null);
                tfEmail.setText(null);
                tfNome.setText(null);
                tfTelefone.setText(null);
                tfCelular.setText(null);
                btgTurno.clearSelection();
                cbxAluno.removeAllItems();
                cbxAluno.removeAllItems();
            } else {
                JOptionPane.showMessageDialog(rootPane, "CPF não e valido");
            }
        }
    }//GEN-LAST:event_btCadastrarConvidadoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenu1ActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miSairActionPerformed

    private void miCadastroConvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroConvidadoActionPerformed
        // TODO add your handling code here:
        CadatroConvidado telaC = new CadatroConvidado(this, true, this.caminhoM, this.usuarioM, this.senhaM);
        telaC.setVisible(true);
    }//GEN-LAST:event_miCadastroConvidadoActionPerformed

    private void miClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClassificacaoActionPerformed
        // TODO add your handling code here:
        TelaClassificacao tela = new TelaClassificacao(this, true, this.caminhoM, this.usuarioM, this.senhaM);
        tela.setVisible(true);
    }//GEN-LAST:event_miClassificacaoActionPerformed

    private void rbMatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMatutinoActionPerformed
        listaTurmaSelecionadaTurno = new ArrayList();
        cbxAluno.removeAllItems();

        for (Turma tur : turmabd.listadeTurma(caminhoM, usuarioM, senhaM)) {
            if (tur.getTurno().trim().equals("MATUTINO")) {
                listaTurmaSelecionadaTurno.add(tur);
                cbxAluno.addItem(tur.getNomeCurso());
            }

        }
    }//GEN-LAST:event_rbMatutinoActionPerformed

    private void rbVespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVespertinoActionPerformed
        cbxAluno.removeAllItems();
        listaTurmaSelecionadaTurno = new ArrayList();

        for (Turma tur : turmabd.listadeTurma(caminhoM, usuarioM, senhaM)) {
            if (tur.getTurno().trim().equals("VESPERTINO")) {
                listaTurmaSelecionadaTurno.add(tur);
                cbxAluno.addItem(tur.getNomeCurso());
            }
        }
    }//GEN-LAST:event_rbVespertinoActionPerformed

    private void rbNoturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoturnoActionPerformed
        listaTurmaSelecionadaTurno = new ArrayList();
        cbxAluno.removeAllItems();
        for (Turma tur : turmabd.listadeTurma(caminhoM, usuarioM, senhaM)) {
            if (tur.getTurno().trim().equals("NOTURNO")) {
                listaTurmaSelecionadaTurno.add(tur);
                cbxAluno.addItem(tur.getNomeCurso());
            }
        }
    }//GEN-LAST:event_rbNoturnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicial("", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarConvidado;
    private javax.swing.ButtonGroup btgTurno;
    private javax.swing.JComboBox cbxAluno;
    private javax.swing.JComboBox cbxEscolaridade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCadastroConvidado;
    private javax.swing.JMenuItem miClassificacao;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JRadioButton rbMatutino;
    private javax.swing.JRadioButton rbNoturno;
    private javax.swing.JRadioButton rbVespertino;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
